### PR TITLE
Raise required php version

### PR DESCRIPTION
**Pull request by rimace**
To php version 7.0, which actually didn't get raised in 1.4.

### CODE REVIEW

**Comment by Ocramius** [comment]
See https://github.com/doctrine/annotations/pull/112

**Comment by webimpress** [comment]
PR https://github.com/doctrine/annotations/pull/112 was _closed_, _not merged, so probably it shouldn't be included in 1.4.0 release notes.

**Comment by mikeSimonson** [comment]
Thanks for the bug report @rimace. I fixed the release notes.

**Comment by tommygnr** [comment]
@mikeSimonson The release notes still claim that PHP 5.x is no longer supported

**Comment by malarzm** [comment]
I see it's updated now, thanks for reminding @tommygnr!

**Pull request closed without merging**
