### PR TITLE
Ignore PHPStan annotation @readonly

### PR DESCRIPTION
**Pull request by gnutix**
see https://github.com/phpstan/phpstan-src/pull/1295

### CODE REVIEW

**Comment by greg0ire** [comment]
Blocked by #440

**Review by greg0ire — APPROVED** [review]

**Review by ostrolucky — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @gnutix !

**Comment by gnutix** [comment]
@greg0ire any chance to see a bugfix release anytime soon ?

**Comment by greg0ire** [comment]
I will work on that today.

**Pull request merged**
