### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by samnela**

### CODE REVIEW

**Comment by samnela** [comment]
Should I change the base branch from master to 1.7 ?

**Comment by malarzm** [comment]
@samnela `master` branch is fine, it's stuck travis that prevents us from merging

**Comment by Majkl578** [comment]
For some reason (unknown to me) Travis rejects builds for this PR and marks them as abusive:

**Comment by Majkl578** [comment]
Alright, let's ignore Travis...

**Comment by stof** [comment]
maybe there is an issue with the Travis setup on this repo.

**Comment by Majkl578** [comment]
Other PRs work fine though, master built fine with this merged as well.
https://travis-ci.org/doctrine/annotations/requests

**Pull request merged**
