### PR TITLE
fix AnnotationReader preParser set ignoreAnnotationNames bug

### PR DESCRIPTION
**Pull request by pinguo-lidanyang**

### CODE REVIEW

**Comment by pinguo-lidanyang** [comment]
with this clode 

`
/**
 * @package Test
 */
class Test
{
      public function get(){}
}

`

when I try to get the annotations of the method 'get', I will get an exception "class package is not exists" in DocParser.php:499 . But the package is the default ignore annotation.

so I find that the preParser does not set the ignore annotation names or namespaces whick causes the bug.

**Comment by alcaeus** [comment]
Please add a test case that fails without your change and passes with it. Thanks!

**Comment by pinguo-lidanyang** [comment]
```
/**
 * Class Test
 * @package TestClass
 */
class TestClass
{
    public function test()
    {

    }
}

$reader = new \Doctrine\Common\Annotations\AnnotationReader();

$ref = new ReflectionMethod(TestClass::class, 'test');

var_dump($reader->getMethodAnnotations($ref));
```


just try this code in php.

**Comment by Ocramius** [comment]
What Andreas asked for is an automated test to be added to the existing
test suite.

**Comment by pinguo-lidanyang** [comment]
Sorry, I made a mistake. I should use this:

```
AnnotationRegistry::registerLoader(function($class){
    if (class_exists($class)) {
        return true;
    }
    return false;
});
```

Thanks for replying. Please close this pr

**Comment by Ocramius** [comment]
You can simplify that to `AnnotationRegistry::
registerLoader('class_exists');`

**Comment by malarzm** [comment]
Closing as per request

**Pull request closed without merging**
