### PR TITLE
[RFC] Parse trait class annotations

### PR DESCRIPTION
**Pull request by kinncj**
The parser wasn't parsing `trait` class annotations as per ticket doctrine/doctrine2#1517

### CODE REVIEW

**Comment by kinncj** [comment]
ping @guilhermeblanco @FabioBatSilva

**Comment by kinncj** [comment]
@FabioBatSilva, @guilhermeblanco, any updates regarding this PR?

**Comment by guilhermeblanco** [comment]
Was supposed to review and merge yesterday.... forgot to do it... =(
Will do during this weekend.

**Comment by mweimerskirch** [comment]
I had issues with this as well using 1.2.7. "Assert" annotations defined inside traits were ignored.
This patch worked for me.

**Comment by nlemahieu** [comment]
:+1: i had the same issue with 1.2.7 and this fix works for me

**Comment by kinncj** [comment]
@guilhermeblanco and @Ocramius doesn't like me... I guess they would never merge...
note for future me: don't drink with Blanco and Pivetta on future #WurstCon

:smile:

**Comment by nlemahieu** [comment]
i can't add the class use on the top of the entity because php-cs-fixer which is included in Travis doesn't like it...

**Comment by deeky666** [comment]
@kinncj this requires a test case.

**Comment by kinncj** [comment]
@deeky666 you must read the description :-)

> The parser wasn't parsing trait class annotations as per ticket doctrine/doctrine2#1517

**Comment by guilhermeblanco** [comment]
@deeky666 this cannot be merged since it may potentially have 2 Traits declaring the same Annotations.

**Comment by kinncj** [comment]
> Some developers are more copy and paster than coders.
Anyway, you are splitting one unique behaviour in two different participants then... the `trait` with `properties` and `HasLifecycleCallbacks`(callbacks) and the annotation for `HasLifecycleCallbacks` in the main participant (class). which means: the class annotation won't work without the trait and the trait won't do anything if the class doesn't annotate that... so instead of a Trait, it's better to just add the `HasLifecycleCallbacks`(the callback methods) to the main participant then.

**Comment by Ocramius** [comment]
Besides https://github.com/doctrine/annotations/pull/63#issuecomment-171659515, extensive testing is *required* before considering anything for merge

**Comment by Majkl578** [comment]
I'm closing this PR because the approach is not correct - merging `use`s of class' scope and traits' scope is not acceptable and may have grave consequences.
See discussion in #102 for alternative and correct approach.

**Pull request closed without merging**
