### PR TITLE
Use void where applicable in the tests directory

### PR DESCRIPTION
**Pull request by greg0ire**
This is a follow-up for what happened in #257 , maybe there would be a way to enforce this in our coding standard?

### CODE REVIEW

**Comment by Ocramius** [comment]
@greg0ire let's close `1.x` from improvements that aren't critical: push this to `master` instead please.

**Comment by greg0ire** [comment]
:confused: phpstan seems to be broken on master…

**Comment by greg0ire** [comment]
> push this to master instead please

Also, do you mean I should use `git push` here? :sweat_smile:

**Comment by Ocramius** [comment]
`master` is broken because of https://github.com/doctrine/annotations/pull/255 - asked original author to check for now, we'll see.

As for pushing to `master`: no please 😜

**Comment by greg0ire** [comment]
> As for pushing to master: no please :stuck_out_tongue_winking_eye: 

I'm relieved :P

**Review by Majkl578 — APPROVED** [review]
This is fine, PHPStan issue is being handled separately: #261

**Pull request merged**
