### PR TITLE
#126 Quotes failing tests - quotes outside an annotation make parsing fail

### PR DESCRIPTION
**Pull request by julienfalque**
See #126.

### CODE REVIEW

**Comment by Ocramius** [comment]
@julienfalque I changed the base branch to `master`. Could you please rebase?

**Comment by julienfalque** [comment]
Done.

**Comment by Ocramius** [comment]
@julienfalque thanks! I won't get to it now, but at least this provides a decent base ground for fixing the issue :-)

**Comment by julienfalque** [comment]
I can try to work on it if that would help.

It looks like all lexer tests assume that it only supports reading from the relevant Annotation part of the DocBlock, not the whole DocBlock itself. Is the lexer failing test case valid? Or should this be fixed in the parser only?

**Comment by Ocramius** [comment]
@julienfalque the lexer is probably not where the bug is: just the parser may be affected. Same tokens, different result expected.

**Comment by julienfalque** [comment]
With `@Foo " @Bar " @Baz`, the lexer does return a string token with `" @Bar "` as value, which is a bug to me.

As a workaround, the parser could simply pass `@Foo`, `@Bar` and `@Baz` successively. The parser already stips the beginning of the DocBlock until it finds the first `@` character (which prevents the bug if the quote is before it). This is why I'm not sure this should be fixed in the lexer (and maybe removing the need to strip the DocBlock) or in the parser (stripping all irrelevant parts instead of just the beginning).

**Comment by greg0ire** [comment]
`master` is probably no longer the right branch for this, I believe 1.8 is now.

**Comment by derrabus** [comment]
Closing as there's no progress to see here.

**Pull request closed without merging**
