### PR TITLE
Pass context in second argument of annotation constructor

### PR DESCRIPTION
**Pull request by zorn-v**

### CODE REVIEW

**Comment by alcaeus** [comment]
Please explain the reason for your patch and add a test for it. Thanks.

**Comment by zorn-v** [comment]
Reason - to show informational errors (e.g. validation in constructor) 
Something like `Parameter "param" is invalid for "@MyAnnotation" in class App\ClassWithAnnotation`

**Comment by zorn-v** [comment]
Test added

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble. Please include the reason you gave in your commit message

How to do that?

1. `git rebase -i origin/1.9`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already push. Don't forget the `--force` option otherwise git will try to merge both things together.

**Comment by beberlei** [comment]
As we move towards #369 with named arguments in constructor for attribute compatibility I will close this PR, as we shouldn't add new minor features anymore.

**Pull request closed without merging**
