### PR TITLE
Merge 1.10.x into master

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by ostrolucky** [comment]
Still draft, are you still working on this?

**Comment by greg0ire** [comment]
@ostrolucky no it's a way to prevent people to merge this, so that we don't end with 2 merge commits. You can still approve though. Please do.

**Comment by greg0ire** [comment]
:thinking: depending on the settings it might not be necessary, let me try to push

**Comment by greg0ire** [comment]
It worked :)

**Pull request merged**
