### PR TITLE
Drop deprecated FileCacheReader

### PR DESCRIPTION
**Pull request by Majkl578**

### CODE REVIEW

**Comment by jwage** [comment]
@Majkl578 needs a rebase.

**Review by lcobucci — CHANGES_REQUESTED** [review]
Changes look great, we do have to update `UPGRADE.md`

**Comment by Majkl578** [comment]
Yes, yes, I keep forgetting (I guess I need `roave/auto-upgrading-generator` 😅 ).

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
> Yes, yes, I keep forgetting

I also forget that all the time

**Pull request merged**
